"""add workflow approval requests

Revision ID: 29962ac6d9a5
Revises: d5f3c474ecbf
Create Date: 2026-07-14 00:01:40.657387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29962ac6d9a5'
down_revision: Union[str, Sequence[str], None] = 'd5f3c474ecbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ebook_item_id', sa.String(length=36), nullable=False),
    sa.Column('approval_type', sa.String(length=32), nullable=False),
    sa.Column('expected_current_status', sa.String(length=32), nullable=False),
    sa.Column('requested_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('request_nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('slack_team_id', sa.String(length=64), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=64), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(approval_type = 'REVIEW_READY' AND expected_current_status = 'REVIEW' AND requested_status = 'READY') OR (approval_type = 'PUBLISH_SCHEDULE' AND expected_current_status = 'READY' AND requested_status = 'SCHEDULED')", name=op.f('ck_workflow_approval_requests_valid_workflow_approval_transition')),
    sa.CheckConstraint("approval_type IN ('REVIEW_READY', 'PUBLISH_SCHEDULE')", name=op.f('ck_workflow_approval_requests_valid_workflow_approval_type')),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'HELD', 'EXPIRED', 'CANCELLED', 'FAILED')", name=op.f('ck_workflow_approval_requests_valid_workflow_approval_status')),
    sa.CheckConstraint('expires_at > requested_at', name=op.f('ck_workflow_approval_requests_valid_workflow_approval_expiration')),
    sa.ForeignKeyConstraint(['ebook_item_id'], ['ebook_items.id'], name=op.f('fk_workflow_approval_requests_ebook_item_id_ebook_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_approval_requests'))
    )
    with op.batch_alter_table('workflow_approval_requests', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_approval_pending_lookup', ['ebook_item_id', 'approval_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_approval_type'), ['approval_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_decided_at'), ['decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_decided_by'), ['decided_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_ebook_item_id'), ['ebook_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_request_nonce_hash'), ['request_nonce_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_slack_channel_id'), ['slack_channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_slack_message_ts'), ['slack_message_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_slack_team_id'), ['slack_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approval_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_slack_team_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_slack_message_ts'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_slack_channel_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_requested_by'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_requested_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_request_nonce_hash'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_expires_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_ebook_item_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_decided_by'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_decided_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_approval_requests_approval_type'))
        batch_op.drop_index('ix_workflow_approval_pending_lookup')

    op.drop_table('workflow_approval_requests')
    # ### end Alembic commands ###
