"""create initial ebook affiliate schema

Revision ID: 77e03a9e5c23
Revises: 
Create Date: 2026-07-13 20:05:37.679152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e03a9e5c23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebook_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=True),
    sa.Column('volume_label', sa.String(length=100), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('publisher_name', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("item_type IN ('tankobon', 'light_novel', 'general_book', 'single_chapter', 'magazine_episode', 'unknown')", name=op.f('ck_ebook_items_valid_item_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ebook_items')),
    sa.UniqueConstraint('source_name', 'source_item_id', name='source_item_identity')
    )
    with op.batch_alter_table('ebook_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ebook_items_author_name'), ['author_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_is_excluded'), ['is_excluded'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_publisher_name'), ['publisher_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_title'), ['title'], unique=False)

    op.create_table('store_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ebook_item_id', sa.String(length=36), nullable=False),
    sa.Column('store_name', sa.String(length=64), nullable=False),
    sa.Column('store_item_id', sa.String(length=255), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('price_yen', sa.Integer(), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('point_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sale_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_rate IS NULL OR (discount_rate >= 0 AND discount_rate <= 100)', name=op.f('ck_store_offers_valid_discount_rate')),
    sa.CheckConstraint('point_rate IS NULL OR (point_rate >= 0 AND point_rate <= 100)', name=op.f('ck_store_offers_valid_point_rate')),
    sa.CheckConstraint('price_yen IS NULL OR price_yen >= 0', name=op.f('ck_store_offers_non_negative_price')),
    sa.ForeignKeyConstraint(['ebook_item_id'], ['ebook_items.id'], name=op.f('fk_store_offers_ebook_item_id_ebook_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_offers')),
    sa.UniqueConstraint('ebook_item_id', 'store_name', 'store_item_id', name='ebook_store_offer_identity')
    )
    with op.batch_alter_table('store_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_offers_ebook_item_id'), ['ebook_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_offers_sale_end_at'), ['sale_end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_offers_sale_start_at'), ['sale_start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_offers_store_name'), ['store_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_offers_store_name'))
        batch_op.drop_index(batch_op.f('ix_store_offers_sale_start_at'))
        batch_op.drop_index(batch_op.f('ix_store_offers_sale_end_at'))
        batch_op.drop_index(batch_op.f('ix_store_offers_ebook_item_id'))

    op.drop_table('store_offers')
    with op.batch_alter_table('ebook_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ebook_items_title'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_release_date'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_publisher_name'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_isbn'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_is_excluded'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_author_name'))

    op.drop_table('ebook_items')
    # ### end Alembic commands ###
