"""add ebook workflow state and history

Revision ID: d5f3c474ecbf
Revises: 77e03a9e5c23
Create Date: 2026-07-13 22:56:00.442379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f3c474ecbf'
down_revision: Union[str, Sequence[str], None] = '77e03a9e5c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ebook_item_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("field_name IN ('workflow_status', 'wordpress_status', 'x_status', 'affiliate_status', 'image_status', 'review_status', 'publish_ready', 'last_error')", name=op.f('ck_workflow_history_valid_workflow_history_field')),
    sa.ForeignKeyConstraint(['ebook_item_id'], ['ebook_items.id'], name=op.f('fk_workflow_history_ebook_item_id_ebook_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_history'))
    )
    with op.batch_alter_table('workflow_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_history_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_history_ebook_item_id'), ['ebook_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_history_field_name'), ['field_name'], unique=False)

    with op.batch_alter_table('ebook_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_status', sa.String(length=32), server_default='NEW', nullable=False))
        batch_op.add_column(sa.Column('wordpress_status', sa.String(length=32), server_default='NOT_CREATED', nullable=False))
        batch_op.add_column(sa.Column('wordpress_post_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('wordpress_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('x_status', sa.String(length=32), server_default='NOT_CREATED', nullable=False))
        batch_op.add_column(sa.Column('x_post_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('affiliate_status', sa.String(length=32), server_default='UNCHECKED', nullable=False))
        batch_op.add_column(sa.Column('image_status', sa.String(length=32), server_default='UNCHECKED', nullable=False))
        batch_op.add_column(sa.Column('review_status', sa.String(length=32), server_default='NOT_REVIEWED', nullable=False))
        batch_op.add_column(sa.Column('publish_ready', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_ebook_items_affiliate_status'), ['affiliate_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_image_status'), ['image_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_publish_ready'), ['publish_ready'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_wordpress_post_id'), ['wordpress_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_wordpress_status'), ['wordpress_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_workflow_status'), ['workflow_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_x_post_id'), ['x_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebook_items_x_status'), ['x_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ebook_items_x_status'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_x_post_id'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_workflow_status'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_wordpress_status'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_wordpress_post_id'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_review_status'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_publish_ready'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_image_status'))
        batch_op.drop_index(batch_op.f('ix_ebook_items_affiliate_status'))
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('last_error')
        batch_op.drop_column('publish_ready')
        batch_op.drop_column('review_status')
        batch_op.drop_column('image_status')
        batch_op.drop_column('affiliate_status')
        batch_op.drop_column('x_post_id')
        batch_op.drop_column('x_status')
        batch_op.drop_column('wordpress_updated_at')
        batch_op.drop_column('wordpress_post_id')
        batch_op.drop_column('wordpress_status')
        batch_op.drop_column('workflow_status')

    with op.batch_alter_table('workflow_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_history_field_name'))
        batch_op.drop_index(batch_op.f('ix_workflow_history_ebook_item_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_history_changed_by'))
        batch_op.drop_index(batch_op.f('ix_workflow_history_changed_at'))

    op.drop_table('workflow_history')
    # ### end Alembic commands ###
